name: Android APK Derleyici

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları Çek
      uses: actions/checkout@v4

    - name: Java Kurulumu (JDK 17)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle 9.3.1 ve Gerekli Bileşenleri Ayarla
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '9.3.1'

    - name: Android Projesini Derle
      run: |
        cd app
        gradle assembleRelease --stacktrace

    - name: APK Dosyasını Çıkart
      uses: actions/upload-artifact@v4
      with:
        name: wp-zamanlayici-release-apk
        path: app/app/build/outputs/apk/release/*.apk
